- characterId: amao
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_amao_glad-001_in
  voiceAssetId: sud_vo_system_amao_produce_fanpresent-01
- characterId: amao
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_amao_glad-003_in
  voiceAssetId: sud_vo_system_amao_produce_fanpresent-02
- characterId: amao
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_amao_idle-001_pose
  voiceAssetId: ""
- characterId: fktn
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_fktn_glad-001_in
  voiceAssetId: sud_vo_system_fktn_produce_fanpresent-01
- characterId: fktn
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_cmmn_koufun-b-002_in
  voiceAssetId: sud_vo_system_fktn_produce_fanpresent-02
- characterId: fktn
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_fktn_idle-001_pose
  voiceAssetId: ""
- characterId: hmsz
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_hmsz_glad-001_in
  voiceAssetId: sud_vo_system_hmsz_produce_fanpresent-01
- characterId: hmsz
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds:
  - mot_all_chr_cmmn_facial-all-jiai1-egao1_in
  bodyAssetIds:
  - mot_all_chr_cmmn_talk-011_in
  voiceAssetId: sud_vo_system_hmsz_produce_fanpresent-02
- characterId: hmsz
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_hmsz_idle-001_pose
  voiceAssetId: ""
- characterId: hrnm
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_hrnm_glad-002_in
  voiceAssetId: sud_vo_system_hrnm_produce_fanpresent-01
- characterId: hrnm
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_hrnm_glad-001_in
  voiceAssetId: sud_vo_system_hrnm_produce_fanpresent-02
- characterId: hrnm
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_hrnm_idle-001_pose
  voiceAssetId: ""
- characterId: hski
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds:
  - mot_all_chr_cmmn_facial-all-tere-ikari1-egao2_in
  bodyAssetIds:
  - mot_all_chr_cmmn_talk-029_in
  voiceAssetId: sud_vo_system_hski_produce_fanpresent-01
- characterId: hski
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_cmmn_glad-a-001_in
  voiceAssetId: sud_vo_system_hski_produce_fanpresent-02
- characterId: hski
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_hski_idle-001_pose
  voiceAssetId: ""
- characterId: hume
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_cmmn_koufun-b-002_in
  voiceAssetId: sud_vo_system_hume_produce_fanpresent-01
- characterId: hume
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_cmmn_tereru-b-002_in
  voiceAssetId: sud_vo_system_hume_produce_fanpresent-02
- characterId: hume
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_hume_idle-001_pose
  voiceAssetId: ""
- characterId: jsna
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds:
  - mot_all_chr_cmmn_facial-all-jiai1-egao1_in
  bodyAssetIds:
  - mot_all_chr_cmmn_talk-027_in
  voiceAssetId: sud_vo_system_jsna_produce_fanpresent-01
- characterId: jsna
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds:
  - mot_all_chr_cmmn_facial-all-toji2-egao1_in
  bodyAssetIds:
  - mot_all_chr_cmmn_talk-007_in
  voiceAssetId: sud_vo_system_jsna_produce_fanpresent-02
- characterId: jsna
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_jsna_idle-001_pose
  voiceAssetId: ""
- characterId: kcna
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_cmmn_yes-b-001_in
  voiceAssetId: sud_vo_system_kcna_produce_fanpresent-01
- characterId: kcna
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_kcna_glad-001_in
  voiceAssetId: sud_vo_system_kcna_produce_fanpresent-02
- characterId: kcna
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_kcna_idle-001_pose
  voiceAssetId: ""
- characterId: kllj
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_kllj_glad-001_in
  voiceAssetId: sud_vo_system_kllj_produce_fanpresent-01
- characterId: kllj
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_kllj_glad-002_in
  voiceAssetId: sud_vo_system_kllj_produce_fanpresent-02
- characterId: kllj
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_kllj_idle-001_pose
  voiceAssetId: ""
- characterId: shro
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_shro_ask-001_in
  voiceAssetId: sud_vo_system_shro_produce_fanpresent-01
- characterId: shro
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_shro_glad-002_in
  voiceAssetId: sud_vo_system_shro_produce_fanpresent-02
- characterId: shro
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_shro_idle-001_pose
  voiceAssetId: ""
- characterId: ssmk
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_ssmk_tanoshimu-001_in
  voiceAssetId: sud_vo_system_ssmk_produce_fanpresent-01
- characterId: ssmk
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_ssmk_glad-001_in
  voiceAssetId: sud_vo_system_ssmk_produce_fanpresent-02
- characterId: ssmk
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_ssmk_idle-001_pose
  voiceAssetId: ""
- characterId: ttmr
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 1
  facialAssetIds:
  - mot_all_chr_cmmn_facial-all-jiai1-egao1_in
  bodyAssetIds:
  - mot_all_chr_cmmn_talk-008_in
  voiceAssetId: sud_vo_system_ttmr_produce_fanpresent-01
- characterId: ttmr
  motionType: ProduceStepFanPresentMotionType_Reaction
  number: 2
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_ttmr_glad-001_in
  voiceAssetId: sud_vo_system_ttmr_produce_fanpresent-02
- characterId: ttmr
  motionType: ProduceStepFanPresentMotionType_Wait
  number: 1
  facialAssetIds: []
  bodyAssetIds:
  - mot_all_chr_ttmr_idle-001_pose
  voiceAssetId: ""