- id: sample_deck_beginner_CardPlayAggressive_group_20_CardPlayAggressive
  label: やる気を増加するスキルカード
  produceCardIds:
  - p_card-02-act-3_038
  - p_card-02-men-2_054
  - p_card-02-men-2_004
  - p_card-02-men-2_053
  - p_card-02-men-2_053
  - p_card-02-men-2_053
  - p_card-02-men-2_053
  - p_card-02-men-1_031
  - p_card-02-men-1_031
  - p_card-02-men-1_031
- id: sample_deck_beginner_CardPlayAggressive_group_20_CardPlayAggressive_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-02-act-2_045
  - p_card-02-act-2_047
  - p_card-02-act-2_047
  - p_card-02-act-1_028
  - p_card-02-act-1_004
  - p_card-02-act-1_004
- id: sample_deck_beginner_CardPlayAggressive_group_20_exam_block
  label: 元気を増加するスキルカード
  produceCardIds:
  - p_card-00-men-3_011
  - p_card-02-men-1_006
  - p_card-00-men-3_012
- id: sample_deck_beginner_CardPlayAggressive_group_35_CardPlayAggressive
  label: やる気を増加するスキルカード
  produceCardIds:
  - p_card-02-act-3_038
  - p_card-02-men-2_054
  - p_card-02-men-2_004
  - p_card-02-men-2_008
  - p_card-02-men-2_008
  - p_card-02-men-2_052
  - p_card-02-men-2_053
  - p_card-02-men-1_032
  - p_card-02-men-1_031
- id: sample_deck_beginner_CardPlayAggressive_group_35_CardPlayAggressive_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-02-act-2_045
  - p_card-02-act-2_047
  - p_card-02-act-2_047
  - p_card-02-act-1_028
  - p_card-02-act-1_004
  - p_card-02-act-1_004
- id: sample_deck_beginner_CardPlayAggressive_group_35_exam_block
  label: 元気を増加するスキルカード
  produceCardIds:
  - p_card-00-men-3_003
  - p_card-02-men-1_006
- id: sample_deck_beginner_CardPlayAggressive_group_35_logic_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-00-men-2_012
  - p_card-02-men-3_002
- id: sample_deck_beginner_CardPlayAggressive_Review_group_20_CardPlayAggressive
  label: やる気を増加するスキルカード
  produceCardIds:
  - p_card-02-act-3_038
  - p_card-02-men-2_054
  - p_card-02-men-2_004
  - p_card-02-men-2_053
  - p_card-02-men-2_053
  - p_card-02-men-1_031
  - p_card-02-men-1_031
  - p_card-02-men-1_031
- id: sample_deck_beginner_CardPlayAggressive_Review_group_20_CardPlayAggressive_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-02-act-2_045
  - p_card-02-act-2_047
  - p_card-02-act-2_047
  - p_card-02-act-1_028
  - p_card-02-act-1_004
  - p_card-02-act-1_004
- id: sample_deck_beginner_CardPlayAggressive_Review_group_20_exam_block
  label: 元気を増加するスキルカード
  produceCardIds:
  - p_card-00-men-3_011
  - p_card-02-men-1_006
  - p_card-00-men-3_012
- id: sample_deck_beginner_CardPlayAggressive_Review_group_20_Review
  label: 好印象を増加するスキルカード
  produceCardIds:
  - p_card-02-men-2_058
  - p_card-02-men-1_009
- id: sample_deck_beginner_CardPlayAggressive_Review_group_35_CardPlayAggressive
  label: やる気を増加するスキルカード
  produceCardIds:
  - p_card-02-men-2_054
  - p_card-02-men-2_004
  - p_card-02-men-2_008
  - p_card-02-men-2_052
  - p_card-02-men-2_053
  - p_card-02-men-2_057
  - p_card-02-men-1_031
- id: sample_deck_beginner_CardPlayAggressive_Review_group_35_CardPlayAggressive_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-02-act-2_045
  - p_card-02-act-1_028
  - p_card-02-act-2_047
  - p_card-02-act-1_004
  - p_card-02-act-1_004
- id: sample_deck_beginner_CardPlayAggressive_Review_group_35_exam_block
  label: 元気を増加するスキルカード
  produceCardIds:
  - p_card-00-men-3_003
  - p_card-02-men-1_006
- id: sample_deck_beginner_CardPlayAggressive_Review_group_35_logic_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-02-men-3_002
  - p_card-00-men-2_012
- id: sample_deck_beginner_CardPlayAggressive_Review_group_35_Review
  label: 好印象を増加するスキルカード
  produceCardIds:
  - p_card-02-men-3_004
  - p_card-02-men-2_058
  - p_card-02-men-2_055
- id: sample_deck_beginner_Concentration_group_20_anomaly_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-00-men-3_011
- id: sample_deck_beginner_Concentration_group_20_anomaly_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-03-act-2_068
  - p_card-03-act-1_044
  - p_card-03-act-1_044
  - p_card-03-act-1_044
- id: sample_deck_beginner_Concentration_group_20_Concentration
  label: 強気に変更するスキルカード
  produceCardIds:
  - p_card-03-act-3_054
  - p_card-03-act-2_065
  - p_card-03-act-2_065
  - p_card-03-act-2_065
  - p_card-03-act-2_065
  - p_card-03-act-2_065
  - p_card-03-act-1_040
- id: |
    sample_deck_beginner_Concentration_group_20_Preservation
  label: 温存に変更するスキルカード
  produceCardIds:
  - p_card-03-men-2_066
  - p_card-03-act-2_073
  - p_card-03-act-2_073
  - p_card-03-men-1_048
  - p_card-03-men-1_039
  - p_card-03-men-1_039
  - p_card-03-men-1_039
- id: sample_deck_beginner_Concentration_group_35_anomaly_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-00-men-2_012
  - p_card-03-men-3_058
- id: sample_deck_beginner_Concentration_group_35_anomaly_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-03-act-2_068
  - p_card-03-act-1_044
  - p_card-03-act-1_044
- id: sample_deck_beginner_Concentration_group_35_Concentration
  label: 強気に変更するスキルカード
  produceCardIds:
  - p_card-03-act-3_056
  - p_card-03-act-3_054
  - p_card-03-act-2_063
  - p_card-03-act-2_063
  - p_card-03-act-2_065
  - p_card-03-act-2_065
  - p_card-03-act-1_040
- id: |
    sample_deck_beginner_Concentration_group_35_Preservation
  label: 温存に変更するスキルカード
  produceCardIds:
  - p_card-03-men-2_066
  - p_card-03-act-2_073
  - p_card-03-men-2_077
  - p_card-03-men-2_077
  - p_card-03-men-1_048
  - p_card-03-men-1_039
  - p_card-03-men-1_039
- id: sample_deck_beginner_FullPower_group_20_anomaly_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-00-men-3_011
- id: sample_deck_beginner_FullPower_group_20_anomaly_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-03-act-2_069
  - p_card-03-act-2_068
  - p_card-03-act-2_068
  - p_card-03-act-3_054
- id: sample_deck_beginner_FullPower_group_20_FullPower
  label: 全力値を増加するスキルカード
  produceCardIds:
  - p_card-03-act-3_057
  - p_card-03-men-2_064
  - p_card-03-men-2_064
  - p_card-03-act-2_072
  - p_card-03-men-1_049
  - p_card-03-men-1_049
  - p_card-03-men-1_049
  - p_card-03-act-1_042
  - p_card-03-act-1_042
  - p_card-03-act-1_038
- id: sample_deck_beginner_FullPower_group_20_Preservation
  label: 温存に変更するスキルカード
  produceCardIds:
  - p_card-03-men-2_066
  - p_card-03-act-2_073
  - p_card-03-act-2_073
  - p_card-03-men-1_039
- id: sample_deck_beginner_FullPower_group_35_anomaly_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-03-men-3_058
  - p_card-00-men-2_012
- id: sample_deck_beginner_FullPower_group_35_anomaly_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-03-act-2_069
  - p_card-03-act-2_068
  - p_card-03-act-3_054
- id: sample_deck_beginner_FullPower_group_35_FullPower
  label: 全力値を増加するスキルカード
  produceCardIds:
  - p_card-03-act-3_057
  - p_card-03-men-2_077
  - p_card-03-men-2_064
  - p_card-03-act-2_072
  - p_card-03-men-1_049
  - p_card-03-men-1_049
  - p_card-03-act-1_042
  - p_card-03-act-1_042
  - p_card-03-act-1_042
  - p_card-03-act-1_038
- id: sample_deck_beginner_FullPower_group_35_Preservation
  label: 温存に変更するスキルカード
  produceCardIds:
  - p_card-03-men-2_066
  - p_card-03-act-2_073
  - p_card-03-act-2_073
  - p_card-03-men-1_039
- id: sample_deck_beginner_LessonBuff_group_20_LessonBuff
  label: 集中を増加するスキルカード
  produceCardIds:
  - p_card-01-men-1_008
  - p_card-01-men-2_038
  - p_card-01-men-2_039
  - p_card-01-men-2_039
  - p_card-01-men-1_024
- id: sample_deck_beginner_LessonBuff_group_20_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-00-men-3_011
- id: sample_deck_beginner_LessonBuff_group_20_ParameterBuff
  label: 好調を増加するスキルカード
  produceCardIds:
  - p_card-01-men-2_035
  - p_card-01-men-2_043
  - p_card-01-men-2_043
  - p_card-01-men-2_043
  - p_card-01-men-1_008
- id: sample_deck_beginner_LessonBuff_group_20_sense_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-01-act-2_033
  - p_card-01-act-3_030
  - p_card-01-act-1_020
  - p_card-01-act-1_020
  - p_card-01-act-2_031
  - p_card-01-act-1_002
  - p_card-01-act-1_022
- id: sample_deck_beginner_LessonBuff_group_35_LessonBuff
  label: 集中を増加するスキルカード
  produceCardIds:
  - p_card-01-men-2_037
  - p_card-01-men-2_040
  - p_card-01-men-2_040
  - p_card-01-men-2_038
  - p_card-01-men-2_039
- id: sample_deck_beginner_LessonBuff_group_35_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-01-men-3_006
  - p_card-00-men-2_012
  - p_card-00-men-3_003
- id: sample_deck_beginner_LessonBuff_group_35_parameter_buff_multiple
  label: 絶好調を増加するスキルカード
  produceCardIds:
  - p_card-01-men-3_036
- id: sample_deck_beginner_LessonBuff_group_35_ParameterBuff
  label: 好調を増加するスキルカード
  produceCardIds:
  - p_card-01-men-2_036
  - p_card-01-men-2_036
  - p_card-01-men-2_035
  - p_card-01-men-2_043
  - p_card-01-men-2_043
- id: sample_deck_beginner_LessonBuff_group_35_sense_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-01-act-2_001
  - p_card-01-act-3_030
  - p_card-01-act-1_022
  - p_card-01-act-1_020
  - p_card-01-act-1_020
- id: sample_deck_beginner_ParameterBuff_group_20_LessonBuff
  label: 集中を増加するスキルカード
  produceCardIds:
  - p_card-01-men-1_008
  - p_card-01-men-2_038
  - p_card-01-men-2_039
  - p_card-01-men-2_039
  - p_card-01-men-1_024
- id: sample_deck_beginner_ParameterBuff_group_20_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-00-men-3_011
- id: sample_deck_beginner_ParameterBuff_group_20_parameter_buff_multiple
  label: 絶好調を増加するスキルカード
  produceCardIds:
  - p_card-01-men-2_034
- id: sample_deck_beginner_ParameterBuff_group_20_ParameterBuff
  label: 好調を増加するスキルカード
  produceCardIds:
  - p_card-01-men-2_035
  - p_card-01-men-2_043
  - p_card-01-men-2_043
  - p_card-01-men-2_043
  - p_card-01-men-1_025
- id: sample_deck_beginner_ParameterBuff_group_20_sense_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-01-act-2_031
  - p_card-01-act-3_031
  - p_card-01-act-1_021
  - p_card-01-act-1_021
  - p_card-01-act-1_002
  - p_card-01-act-1_022
- id: sample_deck_beginner_ParameterBuff_group_35_LessonBuff
  label: 集中を増加するスキルカード
  produceCardIds:
  - p_card-01-men-2_037
  - p_card-01-men-2_040
  - p_card-01-men-2_040
  - p_card-01-men-2_038
  - p_card-01-men-2_039
- id: sample_deck_beginner_ParameterBuff_group_35_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-01-men-3_006
  - p_card-00-men-2_012
  - p_card-00-men-3_003
- id: sample_deck_beginner_ParameterBuff_group_35_parameter_buff_multiple
  label: 絶好調を増加するスキルカード
  produceCardIds:
  - p_card-01-men-3_036
- id: sample_deck_beginner_ParameterBuff_group_35_ParameterBuff
  label: 好調を増加するスキルカード
  produceCardIds:
  - p_card-01-men-2_036
  - p_card-01-men-2_036
  - p_card-01-men-2_043
  - p_card-01-men-2_043
  - p_card-01-men-2_035
- id: sample_deck_beginner_ParameterBuff_group_35_sense_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-01-act-2_001
  - p_card-01-act-3_031
  - p_card-01-act-1_002
  - p_card-01-act-1_021
  - p_card-01-act-1_021
- id: sample_deck_beginner_Review_CardPlayAggressive_group_20_CardPlayAggressive
  label: やる気を増加するスキルカード
  produceCardIds:
  - p_card-02-men-2_004
  - p_card-02-men-1_032
- id: sample_deck_beginner_Review_CardPlayAggressive_group_20_logic_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-00-men-3_011
- id: sample_deck_beginner_Review_CardPlayAggressive_group_20_Review
  label: 好印象を増加するスキルカード
  produceCardIds:
  - p_card-02-men-2_054
  - p_card-02-men-2_058
  - p_card-02-men-2_050
  - p_card-02-men-2_050
  - p_card-02-men-2_050
  - p_card-02-men-2_055
  - p_card-02-men-1_033
  - p_card-02-men-1_030
  - p_card-02-men-1_030
  - p_card-02-men-1_030
  - p_card-02-men-1_030
- id: sample_deck_beginner_Review_CardPlayAggressive_group_20_Review_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-02-act-3_001
  - p_card-02-act-2_046
  - p_card-02-act-1_003
  - p_card-02-act-1_003
  - p_card-02-act-1_003
- id: sample_deck_beginner_Review_CardPlayAggressive_group_35_CardPlayAggressive
  label: やる気を増加するスキルカード
  produceCardIds:
  - p_card-02-men-2_004
  - p_card-02-men-2_057
- id: sample_deck_beginner_Review_CardPlayAggressive_group_35_logic_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-02-men-3_002
  - p_card-00-men-3_003
  - p_card-00-men-2_012
- id: sample_deck_beginner_Review_CardPlayAggressive_group_35_Review
  label: 好印象を増加するスキルカード
  produceCardIds:
  - p_card-02-men-3_004
  - p_card-02-men-2_054
  - p_card-02-men-2_058
  - p_card-02-men-2_050
  - p_card-02-men-2_055
  - p_card-02-men-1_033
  - p_card-02-men-1_030
  - p_card-02-men-1_030
  - p_card-02-men-1_030
- id: sample_deck_beginner_Review_CardPlayAggressive_group_35_Review_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-02-act-2_049
  - p_card-02-act-2_048
  - p_card-02-act-3_001
  - p_card-02-act-1_003
  - p_card-02-act-1_003
- id: sample_deck_beginner_Review_group_20_logic_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-00-men-3_011
- id: sample_deck_beginner_Review_group_20_Review
  label: 好印象を増加するスキルカード
  produceCardIds:
  - p_card-02-men-2_054
  - p_card-02-men-2_058
  - p_card-02-men-2_050
  - p_card-02-men-2_050
  - p_card-02-men-2_050
  - p_card-02-men-2_055
  - p_card-02-men-2_055
  - p_card-02-act-1_027
  - p_card-02-men-1_030
  - p_card-02-men-1_030
  - p_card-02-men-1_030
  - p_card-02-men-1_030
  - p_card-02-men-1_030
- id: sample_deck_beginner_Review_group_20_Review_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-02-act-3_001
  - p_card-02-act-2_046
  - p_card-02-act-1_003
  - p_card-02-act-1_003
  - p_card-02-act-1_003
- id: sample_deck_beginner_Review_group_35_logic_other
  label: その他のスキルカード
  produceCardIds:
  - p_card-02-men-3_002
  - p_card-00-men-2_012
  - p_card-00-men-3_003
- id: sample_deck_beginner_Review_group_35_Review
  label: 好印象を増加するスキルカード
  produceCardIds:
  - p_card-02-men-3_004
  - p_card-02-men-2_054
  - p_card-02-men-2_058
  - p_card-02-men-2_050
  - p_card-02-men-2_050
  - p_card-02-men-2_055
  - p_card-02-men-2_051
  - p_card-02-act-1_027
  - p_card-02-men-1_030
  - p_card-02-men-1_030
  - p_card-02-men-1_030
- id: sample_deck_beginner_Review_group_35_Review_score
  label: スコアを上昇させるスキルカード
  produceCardIds:
  - p_card-02-act-2_048
  - p_card-02-act-3_001
  - p_card-02-act-2_046
  - p_card-02-act-1_003
  - p_card-02-act-1_003