- produceId: produce-004
  characterId: amao
  forceLiveCommonIdolCardId: i_card-amao-3-007
  unlockConditionSetId: cd-dearness_level-amao-10
- produceId: produce-004
  characterId: fktn
  forceLiveCommonIdolCardId: i_card-fktn-3-007
  unlockConditionSetId: cd-dearness_level-fktn-10
- produceId: produce-004
  characterId: hmsz
  forceLiveCommonIdolCardId: i_card-hmsz-3-000
  unlockConditionSetId: cd-story_unlock_hmsz_produce_group-004
- produceId: produce-004
  characterId: hrnm
  forceLiveCommonIdolCardId: i_card-hrnm-3-007
  unlockConditionSetId: cd-dearness_level-hrnm-10
- produceId: produce-004
  characterId: hski
  forceLiveCommonIdolCardId: i_card-hski-3-008
  unlockConditionSetId: cd-dearness_level-hski-10
- produceId: produce-004
  characterId: hume
  forceLiveCommonIdolCardId: i_card-hume-3-006
  unlockConditionSetId: cd-dearness_level-hume-10
- produceId: produce-004
  characterId: jsna
  forceLiveCommonIdolCardId: i_card-jsna-3-002
  unlockConditionSetId: cd-dearness_level-jsna-10
- produceId: produce-004
  characterId: kcna
  forceLiveCommonIdolCardId: i_card-kcna-3-007
  unlockConditionSetId: cd-dearness_level-kcna-10
- produceId: produce-004
  characterId: kllj
  forceLiveCommonIdolCardId: i_card-kllj-3-006
  unlockConditionSetId: cd-dearness_level-kllj-10
- produceId: produce-004
  characterId: shro
  forceLiveCommonIdolCardId: i_card-shro-3-007
  unlockConditionSetId: cd-dearness_level-shro-10
- produceId: produce-004
  characterId: ssmk
  forceLiveCommonIdolCardId: i_card-ssmk-3-007
  unlockConditionSetId: cd-dearness_level-ssmk-10
- produceId: produce-004
  characterId: ttmr
  forceLiveCommonIdolCardId: i_card-ttmr-3-007
  unlockConditionSetId: cd-dearness_level-ttmr-10