- id: highscore-event-001
  name: 十王邦夫のアイドル強化月間
  order: 1
- id: highscore-event-002
  name: ハイスコアイベント
  order: 1
- id: highscore-event-003
  name: ハイスコアイベント
  order: 1
- id: highscore-event-004
  name: ハイスコアイベント
  order: 1