- id: highscore-event-001
  name: 十王邦夫のアイドル強化月間
  produceHighScoreEventType: ProduceHighScoreEventType_Normal
  order: 1
- id: highscore-event-002
  name: ハイスコアイベント
  produceHighScoreEventType: ProduceHighScoreEventType_Normal
  order: 1
- id: highscore-event-003
  name: ハイスコアイベント
  produceHighScoreEventType: ProduceHighScoreEventType_Normal
  order: 1
- id: highscore-event-004
  name: ハイスコアイベント
  produceHighScoreEventType: ProduceHighScoreEventType_Normal
  order: 1
- id: highscorerush-event-001
  name: 十王邦夫のアイドル強化月間・改
  produceHighScoreEventType: ProduceHighScoreEventType_Rush
  order: 1
- id: highscorerush-event-002
  name: 十王邦夫のアイドル強化月間〜星々のきらめき〜
  produceHighScoreEventType: ProduceHighScoreEventType_Rush
  order: 1
- id: highscorerush-event-003
  name: 十王邦夫のアイドル強化月間〜星々のきらめき〜
  produceHighScoreEventType: ProduceHighScoreEventType_Rush
  order: 1