- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_003-group_002
  unlockDescription: 難易度「マスター」の最終試験で1位になる
- id: challenge_slot-exam_card_play_aggressive
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_card_play_aggressive-produce_003-group_003
  unlockDescription: 難易度「マスター」で最終試験に合格して評価S以上を獲得する
- id: challenge_slot-exam_concentration
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_concentration
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_003-group_002
  unlockDescription: 難易度「マスター」の最終試験で1位になる
- id: challenge_slot-exam_concentration
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_concentration-produce_003-group_003
  unlockDescription: 難易度「マスター」で最終試験に合格して評価S以上を獲得する
- id: challenge_slot-exam_full_power
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_full_power
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_003-group_002
  unlockDescription: 難易度「マスター」の最終試験で1位になる
- id: challenge_slot-exam_full_power
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_full_power-produce_003-group_003
  unlockDescription: 難易度「マスター」で最終試験に合格して評価S以上を獲得する
- id: challenge_slot-exam_lesson_buff
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_lesson_buff
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_003-group_002
  unlockDescription: 難易度「マスター」の最終試験で1位になる
- id: challenge_slot-exam_lesson_buff
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_lesson_buff-produce_003-group_003
  unlockDescription: 難易度「マスター」で最終試験に合格して評価S以上を獲得する
- id: challenge_slot-exam_parameter_buff
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_parameter_buff
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_003-group_002
  unlockDescription: 難易度「マスター」の最終試験で1位になる
- id: challenge_slot-exam_parameter_buff
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_parameter_buff-produce_003-group_003
  unlockDescription: 難易度「マスター」で最終試験に合格して評価S以上を獲得する
- id: challenge_slot-exam_review
  produceId: produce-003
  number: 1
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_003-group_001
  unlockDescription: ""
- id: challenge_slot-exam_review
  produceId: produce-003
  number: 2
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_003-group_002
  unlockDescription: 難易度「マスター」の最終試験で1位になる
- id: challenge_slot-exam_review
  produceId: produce-003
  number: 3
  produceItemChallengeGroupId: challenge_slot-exam_review-produce_003-group_003
  unlockDescription: 難易度「マスター」で最終試験に合格して評価S以上を獲得する