- id: CardPlayAggressive_group_20
  description: 『やる気を増加』のスキルカードで構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - CardPlayAggressive_group_20_CardPlayAggressive
  - CardPlayAggressive_group_20_CardPlayAggressive_score
  - CardPlayAggressive_group_20_exam_block
  - CardPlayAggressive_group_20_logic_other
- id: CardPlayAggressive_group_35
  description: 『やる気を増加』のスキルカードで構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - CardPlayAggressive_group_35_CardPlayAggressive
  - CardPlayAggressive_group_35_CardPlayAggressive_score
  - CardPlayAggressive_group_35_exam_block
  - CardPlayAggressive_group_35_logic_other
- id: CardPlayAggressive_Review_group_20
  description: 『やる気を増加』を中心に『好印象を増加』のスキルカードも合わせて構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - CardPlayAggressive_Review_group_20_CardPlayAggressive
  - CardPlayAggressive_Review_group_20_CardPlayAggressive_score
  - CardPlayAggressive_Review_group_20_Review
  - CardPlayAggressive_Review_group_20_exam_block
  - CardPlayAggressive_Review_group_20_other
- id: CardPlayAggressive_Review_group_35
  description: 『やる気を増加』を中心に『好印象を増加』のスキルカードも合わせて構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - CardPlayAggressive_Review_group_35_CardPlayAggressive
  - CardPlayAggressive_Review_group_35_CardPlayAggressive_score
  - CardPlayAggressive_Review_group_35_Review
  - CardPlayAggressive_Review_group_35_exam_block
  - CardPlayAggressive_Review_group_35_logic_other
- id: Concentration_group_20
  description: 『強気に変更』や『温存に変更』のスキルカードをバランスよく構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - Concentration_group_20_Concentration
  - |
    Concentration_group_20_Preservation
  - Concentration_group_20_anomaly_score
  - Concentration_group_20_anomaly_other
- id: Concentration_group_35
  description: 『強気に変更』や『温存に変更』のスキルカードをバランスよく構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - Concentration_group_35_Concentration
  - |
    Concentration_group_35_Preservation
  - Concentration_group_35_anomaly_score
  - Concentration_group_35_anomaly_other
- id: FullPower_group_20
  description: 『全力値を増加』を中心に『温存に変更』のスキルカードも合わせて構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - FullPower_group_20_FullPower
  - FullPower_group_20_Preservation
  - FullPower_group_20_anomaly_score
  - FullPower_group_20_anomaly_other
- id: FullPower_group_35
  description: 『全力値を増加』を中心に『温存に変更』のスキルカードも合わせて構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - FullPower_group_35_FullPower
  - FullPower_group_35_Preservation
  - FullPower_group_35_anomaly_score
  - FullPower_group_35_anomaly_other
- id: LessonBuff_group_20
  description: 『集中を増加』や『好調を増加』のスキルカードをバランスよく構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - LessonBuff_group_20_LessonBuff
  - LessonBuff_group_20_ParameterBuff
  - LessonBuff_group_20_sense_score
  - LessonBuff_group_20_other
- id: LessonBuff_group_35
  description: 『集中を増加』や『好調を増加』のスキルカードをバランスよく構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - LessonBuff_group_35_LessonBuff
  - LessonBuff_group_35_ParameterBuff
  - LessonBuff_group_35_sense_score
  - LessonBuff_group_35_parameter_buff_multiple
  - LessonBuff_group_35_other
- id: ParameterBuff_group_20
  description: 『好調を増加』や『集中を増加』のスキルカードをバランスよく構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - ParameterBuff_group_20_ParameterBuff
  - ParameterBuff_group_20_LessonBuff
  - ParameterBuff_group_20_sense_score
  - ParameterBuff_group_20_parameter_buff_multiple
  - ParameterBuff_group_20_other
- id: ParameterBuff_group_35
  description: 『好調を増加』や『集中を増加』のスキルカードをバランスよく構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - ParameterBuff_group_35_ParameterBuff
  - ParameterBuff_group_35_LessonBuff
  - ParameterBuff_group_35_sense_score
  - ParameterBuff_group_35_parameter_buff_multiple
  - ParameterBuff_group_35_other
- id: Review_CardPlayAggressive_group_20
  description: 『好印象を増加』を中心に『やる気を増加』のスキルカードも合わせて構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - Review_CardPlayAggressive_group_20_Review
  - Review_CardPlayAggressive_group_20_Review_score
  - Review_CardPlayAggressive_group_20_CardPlayAggressive
  - Review_CardPlayAggressive_group_20_logic_other
- id: Review_CardPlayAggressive_group_35
  description: 『好印象を増加』を中心に『やる気を増加』のスキルカードも合わせて構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - Review_CardPlayAggressive_group_35_Review
  - Review_CardPlayAggressive_group_35_Review_score
  - Review_CardPlayAggressive_group_35_CardPlayAggressive
  - Review_CardPlayAggressive_group_35_logic_other
- id: Review_group_20
  description: 『好印象を増加』のスキルカードで構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - Review_group_20_Review
  - Review_group_20_Review_score
  - Review_group_20_logic_other
- id: Review_group_35
  description: 『好印象を増加』のスキルカードで構成するのがおすすめです
  produceGuideProduceCardCategoryIds:
  - Review_group_35_Review
  - Review_group_35_Review_score
  - Review_group_35_logic_other