- id: p_drink_effect-e_effect-exam_block-0003
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_block-0003
- id: p_drink_effect-e_effect-exam_block-0007
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_block-0007
- id: p_drink_effect-e_effect-exam_block-0009
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_block-0009
- id: p_drink_effect-e_effect-exam_card_create_search-0001-p_card_search-random-random_pool-p_random_pool-ssr-upgrade_1-1-hand-random-1_1
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_card_create_search-0001-p_card_search-random-random_pool-p_random_pool-ssr-upgrade_1-1-hand-random-1_1
- id: p_drink_effect-e_effect-exam_card_move-p_card_search-deck_grave-hold-select-1_1
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_card_move-p_card_search-deck_grave-hold-select-1_1
- id: p_drink_effect-e_effect-exam_card_move-p_card_search-deck_grave-idol-unique-1-hand-all-0_0
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_card_move-p_card_search-deck_grave-idol-unique-1-hand-all-0_0
- id: p_drink_effect-e_effect-exam_card_play_aggressive-0003
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_card_play_aggressive-0003
- id: p_drink_effect-e_effect-exam_card_search_effect_play_count_buff-0001-01-01-p_card_search-active_skill-deck_all-all-0_0
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_card_search_effect_play_count_buff-0001-01-01-p_card_search-active_skill-deck_all-all-0_0
- id: p_drink_effect-e_effect-exam_card_upgrade-p_card_search-hand-all-0_0
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_card_upgrade-p_card_search-hand-all-0_0
- id: p_drink_effect-e_effect-exam_concentration-0001
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_concentration-0001
- id: p_drink_effect-e_effect-exam_concentration-0002
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_concentration-0002
- id: p_drink_effect-e_effect-exam_extra_turn
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_extra_turn
- id: p_drink_effect-e_effect-exam_force_play_card_search-p_card_search-random-random_pool-p_random_pool-rush-ssr-upgrade_0-1-hand-random-1_1
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_force_play_card_search-p_card_search-random-random_pool-p_random_pool-rush-ssr-upgrade_1-1-hand-random-1_1
- id: p_drink_effect-e_effect-exam_full_power_point-0001
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_full_power_point-0001
- id: p_drink_effect-e_effect-exam_full_power_point-0002
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_full_power_point-0002
- id: p_drink_effect-e_effect-exam_hand_grave_count_card_draw
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_hand_grave_count_card_draw
- id: p_drink_effect-e_effect-exam_lesson_buff-0003
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_lesson_buff-0003
- id: p_drink_effect-e_effect-exam_lesson_depend_exam_review-1000-01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_lesson_depend_exam_review-1000-01
- id: p_drink_effect-e_effect-exam_lesson_value_multiple-0300-03
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_lesson_value_multiple-0300-03
- id: p_drink_effect-e_effect-exam_lesson-0010-01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_lesson-0010-01
- id: p_drink_effect-e_effect-exam_parameter_buff_multiple_per_turn-01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_parameter_buff_multiple_per_turn-01
- id: p_drink_effect-e_effect-exam_parameter_buff_multiple_per_turn-02
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_parameter_buff_multiple_per_turn-02
- id: p_drink_effect-e_effect-exam_parameter_buff-03
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_parameter_buff-03
- id: p_drink_effect-e_effect-exam_playable_value_add-01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_playable_value_add-01
- id: p_drink_effect-e_effect-exam_preservation-0001
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_preservation-0001
- id: p_drink_effect-e_effect-exam_preservation-0002
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_preservation-0002
- id: p_drink_effect-e_effect-exam_review-0003
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_review-0003
- id: p_drink_effect-e_effect-exam_stamina_consumption_add-01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_stamina_consumption_add-01
- id: p_drink_effect-e_effect-exam_stamina_consumption_down-01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_stamina_consumption_down-01
- id: p_drink_effect-e_effect-exam_stamina_consumption_down-03
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_stamina_consumption_down-03
- id: p_drink_effect-e_effect-exam_stamina_recover_fix-0002
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_stamina_recover_fix-0002
- id: p_drink_effect-e_effect-exam_stamina_recover_fix-0003
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_stamina_recover_fix-0003
- id: p_drink_effect-e_effect-exam_stamina_recover_fix-0006
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_stamina_recover_fix-0006
- id: p_drink_effect-e_effect-exam_stamina_reduce_fix-0002
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_stamina_reduce_fix-0002
- id: p_drink_effect-e_effect-exam_status_enchant-inf-enchant-pdrink_01-3-002-enc01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_status_enchant-inf-enchant-pdrink_01-3-002-enc01
- id: p_drink_effect-e_effect-exam_status_enchant-inf-enchant-pdrink_02-3-006-enc01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_status_enchant-inf-enchant-pdrink_02-3-006-enc01
- id: p_drink_effect-e_effect-exam_status_enchant-inf-enchant-pdrink_02-3-007-enc01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_status_enchant-inf-enchant-pdrink_02-3-007-enc01
- id: p_drink_effect-e_effect-exam_status_enchant-inf-enchant-pdrink_03-3-008-enc01
  produceEffectId: ""
  produceExamEffectId: e_effect-exam_status_enchant-inf-enchant-pdrink_03-3-008-enc01