- id: CardPlayAggressive_group_20
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_CardPlayAggressive_group_20_CardPlayAggressive
  - sample_deck_beginner_CardPlayAggressive_group_20_CardPlayAggressive_score
  - sample_deck_beginner_CardPlayAggressive_group_20_exam_block
- id: CardPlayAggressive_group_35
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_CardPlayAggressive_group_35_CardPlayAggressive
  - sample_deck_beginner_CardPlayAggressive_group_35_CardPlayAggressive_score
  - sample_deck_beginner_CardPlayAggressive_group_35_exam_block
  - sample_deck_beginner_CardPlayAggressive_group_35_logic_other
- id: CardPlayAggressive_Review_group_20
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_CardPlayAggressive_Review_group_20_CardPlayAggressive
  - sample_deck_beginner_CardPlayAggressive_Review_group_20_CardPlayAggressive_score
  - sample_deck_beginner_CardPlayAggressive_Review_group_20_Review
  - sample_deck_beginner_CardPlayAggressive_Review_group_20_exam_block
- id: CardPlayAggressive_Review_group_35
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_CardPlayAggressive_Review_group_35_CardPlayAggressive
  - sample_deck_beginner_CardPlayAggressive_Review_group_35_CardPlayAggressive_score
  - sample_deck_beginner_CardPlayAggressive_Review_group_35_Review
  - sample_deck_beginner_CardPlayAggressive_Review_group_35_exam_block
  - sample_deck_beginner_CardPlayAggressive_Review_group_35_logic_other
- id: Concentration_group_20
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_Concentration_group_20_Concentration
  - |
    sample_deck_beginner_Concentration_group_20_Preservation
  - sample_deck_beginner_Concentration_group_20_anomaly_score
  - sample_deck_beginner_Concentration_group_20_anomaly_other
- id: Concentration_group_35
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_Concentration_group_35_Concentration
  - |
    sample_deck_beginner_Concentration_group_35_Preservation
  - sample_deck_beginner_Concentration_group_35_anomaly_score
  - sample_deck_beginner_Concentration_group_35_anomaly_other
- id: FullPower_group_20
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_FullPower_group_20_FullPower
  - sample_deck_beginner_FullPower_group_20_Preservation
  - sample_deck_beginner_FullPower_group_20_anomaly_score
  - sample_deck_beginner_FullPower_group_20_anomaly_other
- id: FullPower_group_35
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_FullPower_group_35_FullPower
  - sample_deck_beginner_FullPower_group_35_Preservation
  - sample_deck_beginner_FullPower_group_35_anomaly_score
  - sample_deck_beginner_FullPower_group_35_anomaly_other
- id: LessonBuff_group_20
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_LessonBuff_group_20_LessonBuff
  - sample_deck_beginner_LessonBuff_group_20_ParameterBuff
  - sample_deck_beginner_LessonBuff_group_20_sense_score
  - sample_deck_beginner_LessonBuff_group_20_other
- id: LessonBuff_group_35
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_LessonBuff_group_35_LessonBuff
  - sample_deck_beginner_LessonBuff_group_35_ParameterBuff
  - sample_deck_beginner_LessonBuff_group_35_sense_score
  - sample_deck_beginner_LessonBuff_group_35_parameter_buff_multiple
  - sample_deck_beginner_LessonBuff_group_35_other
- id: ParameterBuff_group_20
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_ParameterBuff_group_20_ParameterBuff
  - sample_deck_beginner_ParameterBuff_group_20_LessonBuff
  - sample_deck_beginner_ParameterBuff_group_20_sense_score
  - sample_deck_beginner_ParameterBuff_group_20_parameter_buff_multiple
  - sample_deck_beginner_ParameterBuff_group_20_other
- id: ParameterBuff_group_35
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_ParameterBuff_group_35_ParameterBuff
  - sample_deck_beginner_ParameterBuff_group_35_LessonBuff
  - sample_deck_beginner_ParameterBuff_group_35_sense_score
  - sample_deck_beginner_ParameterBuff_group_35_parameter_buff_multiple
  - sample_deck_beginner_ParameterBuff_group_35_other
- id: Review_CardPlayAggressive_group_20
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_Review_CardPlayAggressive_group_20_Review
  - sample_deck_beginner_Review_CardPlayAggressive_group_20_Review_score
  - sample_deck_beginner_Review_CardPlayAggressive_group_20_CardPlayAggressive
  - sample_deck_beginner_Review_CardPlayAggressive_group_20_logic_other
- id: Review_CardPlayAggressive_group_35
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_Review_CardPlayAggressive_group_35_Review
  - sample_deck_beginner_Review_CardPlayAggressive_group_35_Review_score
  - sample_deck_beginner_Review_CardPlayAggressive_group_35_CardPlayAggressive
  - sample_deck_beginner_Review_CardPlayAggressive_group_35_logic_other
- id: Review_group_20
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_Review_group_20_Review
  - sample_deck_beginner_Review_group_20_Review_score
  - sample_deck_beginner_Review_group_20_logic_other
- id: Review_group_35
  produceGuideProduceCardSampleDeckCategoryIds:
  - sample_deck_beginner_Review_group_35_Review
  - sample_deck_beginner_Review_group_35_Review_score
  - sample_deck_beginner_Review_group_35_logic_other