- type: ProduceCardGrowEffectType_LessonAdd
  name: パラメータ値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonAdd
  produceCardCustomizeDescription: パラメータ+
- type: ProduceCardGrowEffectType_LessonReduce
  name: パラメータ値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonReduce
  produceCardCustomizeDescription: パラメータ-
- type: ProduceCardGrowEffectType_LessonCountAdd
  name: パラメータ上昇回数増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonCountAdd
  produceCardCustomizeDescription: "パラメータ\\n上昇回数+"
- type: ProduceCardGrowEffectType_LessonCountReduce
  name: パラメータ上昇回数減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonCountReduce
  produceCardCustomizeDescription: "パラメータ\\n上昇回数-"
- type: ProduceCardGrowEffectType_BlockAdd
  name: 元気値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_BlockAdd
  produceCardCustomizeDescription: 元気+
- type: ProduceCardGrowEffectType_BlockReduce
  name: 元気値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_BlockReduce
  produceCardCustomizeDescription: 元気-
- type: ProduceCardGrowEffectType_FullPowerPointAdd
  name: 全力値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_FullPowerPointAdd
  produceCardCustomizeDescription: 全力値+
- type: ProduceCardGrowEffectType_FullPowerPointReduce
  name: 全力値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_FullPowerPointReduce
  produceCardCustomizeDescription: 全力値-
- type: ProduceCardGrowEffectType_CostBuffReduce
  name: 強化状態コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostBuffReduce
  produceCardCustomizeDescription: 強化状態コスト値-
- type: ProduceCardGrowEffectType_CostBuffAdd
  name: 強化状態コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostBuffAdd
  produceCardCustomizeDescription: 強化状態コスト値+
- type: ProduceCardGrowEffectType_CostReduce
  name: コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostReduce
  produceCardCustomizeDescription: コスト値-
- type: ProduceCardGrowEffectType_CostAdd
  name: コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostAdd
  produceCardCustomizeDescription: コスト値+
- type: ProduceCardGrowEffectType_CostPenetrateReduce
  name: 体力消費コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostPenetrateReduce
  produceCardCustomizeDescription: 体力消費コスト値-
- type: ProduceCardGrowEffectType_CostPenetrateAdd
  name: 体力消費コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostPenetrateAdd
  produceCardCustomizeDescription: 体力消費コスト値+
- type: ProduceCardGrowEffectType_ParameterBuffTurnAdd
  name: 好調値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_ParameterBuffTurnAdd
  produceCardCustomizeDescription: 好調+
- type: ProduceCardGrowEffectType_ParameterBuffTurnReduce
  name: 好調値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_ParameterBuffTurnReduce
  produceCardCustomizeDescription: 好調-
- type: ProduceCardGrowEffectType_LessonBuffAdd
  name: 集中値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonBuffAdd
  produceCardCustomizeDescription: 集中+
- type: ProduceCardGrowEffectType_LessonBuffReduce
  name: 集中値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonBuffReduce
  produceCardCustomizeDescription: 集中-
- type: ProduceCardGrowEffectType_ReviewAdd
  name: 好印象値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_ReviewAdd
  produceCardCustomizeDescription: 好印象+
- type: ProduceCardGrowEffectType_ReviewReduce
  name: 好印象値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_ReviewReduce
  produceCardCustomizeDescription: 好印象-
- type: ProduceCardGrowEffectType_AggressiveAdd
  name: やる気値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_AggressiveAdd
  produceCardCustomizeDescription: やる気+
- type: ProduceCardGrowEffectType_AggressiveReduce
  name: やる気値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_AggressiveReduce
  produceCardCustomizeDescription: やる気-
- type: ProduceCardGrowEffectType_CardDrawAdd
  name: ドロー枚数増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CardDrawAdd
  produceCardCustomizeDescription: カードを引く+
- type: ProduceCardGrowEffectType_CardDrawReduce
  name: ドロー枚数減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CardDrawReduce
  produceCardCustomizeDescription: カードを引く-
- type: ProduceCardGrowEffectType_ParameterBuffMultiplePerTurnAdd
  name: 絶好調値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_ParameterBuffMultiplePerTurnAdd
  produceCardCustomizeDescription: 絶好調+
- type: ProduceCardGrowEffectType_ParameterBuffMultiplePerTurnReduce
  name: 絶好調値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_ParameterBuffMultiplePerTurnReduce
  produceCardCustomizeDescription: 絶好調-
- type: ProduceCardGrowEffectType_StaminaConsumptionDownTurnAdd
  name: 消費体力減少値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_StaminaConsumptionDownTurnAdd
  produceCardCustomizeDescription: 消費体力減少+
- type: ProduceCardGrowEffectType_StaminaConsumptionDownTurnReduce
  name: 消費体力減少値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_StaminaConsumptionDownTurnReduce
  produceCardCustomizeDescription: 消費体力減少-
- type: ProduceCardGrowEffectType_StaminaConsumptionAddTurnAdd
  name: 消費体力増加値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_StaminaConsumptionAddTurnAdd
  produceCardCustomizeDescription: 消費体力増加+
- type: ProduceCardGrowEffectType_StaminaConsumptionAddTurnReduce
  name: 消費体力増加値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_StaminaConsumptionAddTurnReduce
  produceCardCustomizeDescription: 消費体力増加-
- type: ProduceCardGrowEffectType_EffectAdd
  name: 効果追加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_EffectAdd
  produceCardCustomizeDescription: 効果追加
- type: ProduceCardGrowEffectType_EffectDelete
  name: 効果削除
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_EffectDelete
  produceCardCustomizeDescription: 効果削除
- type: ProduceCardGrowEffectType_EffectChange
  name: 効果置換
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_EffectChange
  produceCardCustomizeDescription: 効果変更
- type: ProduceCardGrowEffectType_CardStatusEnchantChange
  name: 成長効果置換
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CardStatusEnchantChange
  produceCardCustomizeDescription: 成長
- type: ProduceCardGrowEffectType_PlayTriggerChange
  name: 使用可能条件を置換
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_PlayTriggerChange
  produceCardCustomizeDescription: 条件変更
- type: ProduceCardGrowEffectType_PlayEffectTriggerChange
  name: 効果発動条件を置換
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_PlayEffectTriggerChange
  produceCardCustomizeDescription: 条件変更
- type: ProduceCardGrowEffectType_PlayMovePositionTypeChange
  name: 使用後移動先変更
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_PlayMovePositionTypeChange
  produceCardCustomizeDescription: 移動先変更
- type: ProduceCardGrowEffectType_InitialAdd
  name: 開始時手札効果付与
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_InitialAdd
  produceCardCustomizeDescription: 開始時手札に入る
- type: ProduceCardGrowEffectType_CostLessonBuffReduce
  name: 集中コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostLessonBuffReduce
  produceCardCustomizeDescription: 集中コスト値-
- type: ProduceCardGrowEffectType_CostLessonBuffAdd
  name: 集中コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostLessonBuffAdd
  produceCardCustomizeDescription: 集中コスト値+
- type: ProduceCardGrowEffectType_CostReviewReduce
  name: 好印象コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostReviewReduce
  produceCardCustomizeDescription: 好印象コスト値-
- type: ProduceCardGrowEffectType_CostReviewAdd
  name: 好印象コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostReviewAdd
  produceCardCustomizeDescription: 好印象コスト値+
- type: ProduceCardGrowEffectType_CostAggressiveReduce
  name: やる気コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostAggressiveReduce
  produceCardCustomizeDescription: やる気コスト値-
- type: ProduceCardGrowEffectType_CostAggressiveAdd
  name: やる気コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostAggressiveAdd
  produceCardCustomizeDescription: やる気コスト値+
- type: ProduceCardGrowEffectType_CostParameterBuffReduce
  name: 好調コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostParameterBuffReduce
  produceCardCustomizeDescription: 好調コスト値-
- type: ProduceCardGrowEffectType_CostParameterBuffAdd
  name: 好調コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostParameterBuffAdd
  produceCardCustomizeDescription: 好調コスト値+
- type: ProduceCardGrowEffectType_CostFullPowerPointReduce
  name: 全力値コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostFullPowerPointReduce
  produceCardCustomizeDescription: 全力値コスト値-
- type: ProduceCardGrowEffectType_CostFullPowerPointAdd
  name: 全力値コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostFullPowerPointAdd
  produceCardCustomizeDescription: 全力値コスト値+
- type: ProduceCardGrowEffectType_LessonDependBlockAdd
  name: 元気分パラメータ倍率増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonDependBlockAdd
  produceCardCustomizeDescription: 元気分パラメータ+
- type: ProduceCardGrowEffectType_LessonDependExamCardPlayAggressiveAdd
  name: やる気分パラメータ倍率増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonDependExamCardPlayAggressiveAdd
  produceCardCustomizeDescription: やる気分パラメータ+
- type: ProduceCardGrowEffectType_LessonDependExamReviewAdd
  name: 好印象分パラメータ倍率増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_LessonDependExamReviewAdd
  produceCardCustomizeDescription: 好印象分パラメータ+
- type: ProduceCardGrowEffectType_CostParameterBuffMultiplePerTurnAdd
  name: 絶好調コスト値増加
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostParameterBuffMultiplePerTurnAdd
  produceCardCustomizeDescription: 絶好調コスト値+
- type: ProduceCardGrowEffectType_CostParameterBuffMultiplePerTurnReduce
  name: 絶好調コスト値減少
  noIcon: false
  noReference: false
  produceDescriptionLabelId: Label_CostParameterBuffMultiplePerTurnReduce
  produceCardCustomizeDescription: 絶好調コスト値-